language: elixir

matrix:
  include:
    - otp_release: 18.3
      elixir: 1.3.1
    - otp_release: 19.0
      elixir: 1.3.1
    - otp_release: 19.1
      elixir: 1.4.0

script:
  - bin/start-toxiproxy.sh
  - mix test --trace
